### ISSUE TITLE
иконки металлов

### ISSUE THREAD

**Issue by zakaratcha** [impullsss/4pcs9_site#13]
![metal-icons](https://user-images.githubusercontent.com/2573820/49996121-2dea1a80-ff9f-11e8-98ad-dc0cda4a23d7.jpg)

Добавить наглядные картинки к перечню металлов. На картинках должны быть изображены собственно металлы.

Иконки сделать круглыми (средствами css). При наведении они должны увеличиваться.

Сами картинки нарыть в интернете.

**Comment by elmazbekirova** [comment]
Беру это на себя)
