### ISSUE TITLE
Перенести раздел "Персонал"

### ISSUE THREAD

**Issue by zakaratcha** [impullsss/4pcs9_site#6]
Блок "Наша команда" (пункт меню "Персонал") унести в самый низ. И заголовок можно изменить на "Авторы сайта".

Цель этого сайта - рассказать о проблеме утилизации батареек и путях решения этой проблемы. Так что рассказ о вашей замечательной команде - не самая важная информация.

**Comment by impullsss** [comment]
Выполнил.
